[DEFAULT]

[application-config]
output.file.header.columnnames=["brokerage_account_number","transaction_id","transaction_date","transaction_type","transaction_desc","symbol","name","source_shares","currency","source_price_per_share","source_fees","source_commissions","source_transaction_amount","normalized_shares","normalized_transaction_amount","transaction_notes"]
error.file.header.columnnames=["brokerage_account_number","transaction_id","transaction_date","transaction_type","transaction_desc","symbol","name","source_shares","currency","source_price_per_share","source_fees","source_commissions","source_transaction_amount","normalized_shares","normalized_transaction_amount","transaction_notes","errors"]

[mysql-app-config]
# escape % with %%
mysql.transactions_stage_unique.insert=insert into finance.transactions_staging_unique (brokerage_account_number,transaction_uuid,transaction_date,transaction_type,transaction_desc,symbol,name,source_shares,source_price_per_share,source_fees,source_commissions,source_transaction_amount) values (%%(brokerage_account_number)s,%%(transaction_id)s,%%(transaction_date)s,%%(transaction_type)s,%%(transaction_desc)s,%%(symbol)s,%%(name)s,%%(source_shares)s,%%(source_price_per_share)s,%%(source_fees)s,%%(source_commissions)s,%%(source_transaction_amount)s)

[Brokerage-processor]
row.processor.module=fidelity_transaction_row_processor
row.processor.class=BrokerageTransactionRowProcessor

[SMA-processor]
row.processor.module=fidelity_transaction_row_processor
row.processor.class=SMATransactionRowProcessor

[Redrive-processor]
row.processor.module=output_file_redrive_row_processor
row.processor.class=RedriveTransactionRowProcessor

[Empower-processor]
row.processor.module=empower_transaction_row_processor
row.processor.class=EmpowerTransactionRowProcessor